# Generated by Django 3.2.6 on 2022-07-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subjectteacher',
            name='Unique Subject Teacher',
        ),
        migrations.AddConstraint(
            model_name='subjectteacher',
            constraint=models.UniqueConstraint(fields=('teacher', 'subject', 'semester'), name='Unique Subject Teacher'),
        ),
    ]
